import os

from decouple import config

SOURCE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SOURCE_DIR)

REDIS_ADDRESS = config('REDIS_ADDRESS', default='localhost')
REDIS_PORT = config('REDIS_PORT', default='6379')

TRACER_REPORTING_HOST = config('TRACER_REPORTING_HOST', default='localhost')
TRACER_REPORTING_PORT = config('TRACER_REPORTING_PORT', default='6831')


SERVICE_STREAM_KEY = config('SERVICE_STREAM_KEY')


LISTEN_EVENT_TYPE_PUBLISHER_CREATED = config('LISTEN_EVENT_TYPE_PUBLISHER_CREATED')
LISTEN_EVENT_TYPE_PUBLISHER_REMOVED = config('LISTEN_EVENT_TYPE_PUBLISHER_REMOVED')
LISTEN_EVENT_TYPE_QUERY_RECEIVED = config('LISTEN_EVENT_TYPE_QUERY_RECEIVED')
LISTEN_EVENT_TYPE_QUERY_DELETION_REQUESTED = config('LISTEN_EVENT_TYPE_QUERY_DELETION_REQUESTED')
LISTEN_EVENT_TYPE_SERVICE_WORKER_ANNOUNCED = config('LISTEN_EVENT_TYPE_SERVICE_WORKER_ANNOUNCED')

SERVICE_CMD_KEY_LIST = [
    LISTEN_EVENT_TYPE_PUBLISHER_CREATED,
    LISTEN_EVENT_TYPE_PUBLISHER_REMOVED,
    LISTEN_EVENT_TYPE_QUERY_RECEIVED,
    LISTEN_EVENT_TYPE_QUERY_DELETION_REQUESTED,
    LISTEN_EVENT_TYPE_SERVICE_WORKER_ANNOUNCED,
]

PUB_EVENT_TYPE_QUERY_CREATED = config('PUB_EVENT_TYPE_QUERY_CREATED')
PUB_EVENT_TYPE_QUERY_REMOVED = config('PUB_EVENT_TYPE_QUERY_REMOVED')

PUB_EVENT_LIST = [
    PUB_EVENT_TYPE_QUERY_CREATED,
    PUB_EVENT_TYPE_QUERY_REMOVED,
]


SERVICE_DETAILS = None


LOGGING_LEVEL = config('LOGGING_LEVEL', default='DEBUG')
